# Generated by Django 4.2.7 on 2026-04-03 07:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_period",
                    models.CharField(
                        help_text="Ví dụ: Q1-2026, H1-2026", max_length=50
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "work_quality",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "work_efficiency",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "teamwork",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "initiative",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=1, default=3.0, max_digits=3),
                ),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                ("goals_next_period", models.TextField(blank=True)),
                ("reviewer_comments", models.TextField(blank=True)),
                ("employee_comments", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("submitted", "Đã gửi"),
                            ("acknowledged", "Đã xác nhận"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "year"],
                        name="performance_employe_c95c4a_idx",
                    )
                ],
                "unique_together": {("employee", "review_period", "year")},
            },
        ),
        migrations.CreateModel(
            name="KPIGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("q1", "Quý 1"),
                            ("q2", "Quý 2"),
                            ("q3", "Quý 3"),
                            ("q4", "Quý 4"),
                            ("h1", "6 tháng đầu"),
                            ("h2", "6 tháng cuối"),
                            ("annual", "Cả năm"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "actual_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Ví dụ: %, triệu VNĐ, đơn hàng",
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Trọng số (%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang thực hiện"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_kpis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "period"],
                "indexes": [
                    models.Index(
                        fields=["employee", "year", "period"],
                        name="performance_employe_1891fe_idx",
                    )
                ],
            },
        ),
    ]
