# Generated by Django 4.2.7 on 2026-03-31 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payslips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hrannouncement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["employee", "month_year"], name="employees_p_employe_129d0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(fields=["status"], name="employees_p_status_27d759_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together={("employee", "month_year")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="employees_l_employe_cc1aa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="employees_l_start_d_844d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrannouncement",
            index=models.Index(
                fields=["status", "published_at"], name="employees_h_status_da5945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["employee_id"], name="employees_e_employe_1c383a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["department"], name="employees_e_departm_8a0787_idx"
            ),
        ),
    ]
