# Generated by Django 4.2.7 on 2026-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employeeprofile_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrannouncement",
            name="target_department",
            field=models.CharField(
                choices=[
                    ("hr", "Nhân sự"),
                    ("it", "Công nghệ Thông tin"),
                    ("sales", "Kinh doanh"),
                    ("marketing", "Marketing"),
                    ("operations", "Vận hành"),
                    ("finance", "Tài chính"),
                    ("all", "Tất cả"),
                ],
                default="all",
                help_text="Target department for this announcement, or 'all' for company-wide",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="administrativerequest",
            name="priority",
            field=models.CharField(
                choices=[("low", "Thấp"), ("medium", "Trung bình"), ("high", "Cao")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="administrativerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("employment_verification", "Xác nhận công tác"),
                    ("card_replacement", "Cấp lại thẻ"),
                    ("salary_certificate", "Giấy xác nhận lương"),
                    ("experience_letter", "Giấy xác nhận kinh nghiệm"),
                    ("other", "Khác"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="administrativerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("in_progress", "Đang xử lý"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Từ chối"),
                    ("completed", "Hoàn thành"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("hr", "Nhân sự"),
                    ("it", "Công nghệ Thông tin"),
                    ("sales", "Kinh doanh"),
                    ("marketing", "Marketing"),
                    ("operations", "Vận hành"),
                    ("finance", "Tài chính"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hrannouncement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("published", "Đã xuất bản"),
                    ("archived", "Lưu trữ"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Nghỉ ốm"),
                    ("casual", "Nghỉ việc riêng"),
                    ("earned", "Nghỉ phép năm"),
                    ("maternity", "Nghỉ thai sản"),
                    ("paternity", "Nghỉ chăm con"),
                    ("unpaid", "Nghỉ không lương"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Từ chối"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="month_year",
            field=models.DateField(help_text="Ngày đầu tiên của tháng cho phiếu lương"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("finalized", "Đã hoàn tất"),
                    ("distributed", "Đã phát"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
