# Generated by Django 4.2.7 on 2026-03-31 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentaccesslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document"], name="documents_d_documen_083a67_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["document", "accessed_at"],
                name="documents_d_documen_aff523_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["user", "accessed_at"], name="documents_d_user_id_cd7fb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "is_indexed"], name="documents_d_status_1f3484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_d_documen_40c475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="documents_d_uploade_6455fb_idx"
            ),
        ),
    ]
