# Generated by Django 4.2.7 on 2026-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="department",
            field=models.CharField(
                choices=[
                    ("hr", "Nhân sự"),
                    ("it", "Công nghệ Thông tin"),
                    ("sales", "Kinh doanh"),
                    ("marketing", "Marketing"),
                    ("operations", "Vận hành"),
                    ("finance", "Tài chính"),
                    ("company", "Toàn công ty"),
                ],
                default="company",
                help_text="Department this document belongs to, or 'company' for company-wide",
                max_length=50,
            ),
        ),
    ]
