# Generated by Django 4.2.7 on 2026-04-07 03:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="late_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Số phút đi muộn so với 8:30"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="penalty_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tiền phạt (0 nếu đúng giờ hoặc đã được tha)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="LatePardon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(help_text="Lý do xin tha tội")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã tha"),
                            ("rejected", "Từ chối – bị phạt"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_comment", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="late_pardons_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_pardon",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
