# Generated by Django 4.2.7 on 2026-04-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("asset_code", models.CharField(max_length=50, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("desktop", "Máy tính để bàn"),
                            ("phone", "Điện thoại"),
                            ("tablet", "Máy tính bảng"),
                            ("monitor", "Màn hình"),
                            ("keyboard", "Bàn phím / Chuột"),
                            ("headset", "Tai nghe"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Mới"),
                            ("good", "Tốt"),
                            ("fair", "Trung bình"),
                            ("poor", "Kém"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Sẵn sàng"),
                            ("assigned", "Đã bàn giao"),
                            ("maintenance", "Bảo trì"),
                            ("retired", "Đã thanh lý"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["asset_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["asset_type", "status"],
                        name="assets_comp_asset_t_b4d5bb_idx",
                    ),
                    models.Index(
                        fields=["asset_code"], name="assets_comp_asset_c_00a291_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "condition_on_assign",
                    models.CharField(
                        choices=[
                            ("new", "Mới"),
                            ("good", "Tốt"),
                            ("fair", "Trung bình"),
                            ("poor", "Kém"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "condition_on_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Mới"),
                            ("good", "Tốt"),
                            ("fair", "Trung bình"),
                            ("poor", "Kém"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assets.companyasset",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="assets_asse_employe_b2486a_idx",
                    ),
                    models.Index(
                        fields=["asset", "is_active"],
                        name="assets_asse_asset_i_4e48bb_idx",
                    ),
                ],
            },
        ),
    ]
