# Generated by Django 4.2.7 on 2026-04-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_request", "Đơn nghỉ phép"),
                            ("leave_approved", "Nghỉ phép được duyệt"),
                            ("leave_rejected", "Nghỉ phép bị từ chối"),
                            ("wfh_request", "Đơn WFH"),
                            ("wfh_approved", "WFH được duyệt"),
                            ("overtime_request", "Đơn tăng ca"),
                            ("overtime_approved", "Tăng ca được duyệt"),
                            ("expense_submitted", "Đơn hoàn tiền gửi"),
                            ("expense_approved", "Hoàn tiền được duyệt"),
                            ("payslip_available", "Phiếu lương mới"),
                            ("announcement", "Thông báo mới"),
                            ("contract_expiring", "Hợp đồng sắp hết hạn"),
                            ("admin_request", "Yêu cầu hành chính"),
                            ("performance_review", "Đánh giá hiệu suất"),
                            ("training_enroll", "Đăng ký đào tạo"),
                            ("asset_assigned", "Bàn giao tài sản"),
                            ("general", "Thông báo chung"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("related_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
    ]
